sudo: false

language: node_js
node_js:
- '4'
- '5'
- '6'
- '7'

cache:
  directories:
    - node_modules

before_install:
  - if [[ `npm -v` != 3* ]]; then npm i -g npm@3; fi
  - cd src/CoreDataStore.Web
script:
  - npm run clean
  - npm run build
# after_script: 'gulp coveralls'

notifications:
  slack: leduong:8FHnajypcfOykiQS6Hn6QBB5